"""Publication-quality attention pattern and induction score figures (Matplotlib).

Figure standards: colourblind-safe viridis/tab10, 10pt labels, 12pt titles.
All figures saved as PDF (vector) + PNG (300 dpi).
All paper figures generated by notebooks/05_figures.ipynb — never edited manually.
"""
from __future__ import annotations
import logging
from pathlib import Path
from typing import Optional

import matplotlib.pyplot as plt
import numpy as np
import torch
import transformer_lens

logger = logging.getLogger(__name__)
LABEL_FONTSIZE = 10
TITLE_FONTSIZE = 12


def _save(fig: plt.Figure, path: Path, dpi: int = 300) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(path.with_suffix(".png"), bbox_inches="tight", dpi=dpi)
    logger.info("Figure saved: %s (.pdf + .png)", path)


def plot_attention_heatmap(
    model: transformer_lens.HookedTransformer,
    tokens: torch.Tensor,
    layer: int,
    head: int,
    token_labels: Optional[list[str]] = None,
    title: Optional[str] = None,
    save_path: Optional[Path] = None,
    device: Optional[str] = None,
) -> plt.Figure:
    """Attention pattern heatmap for a single head (Figure 2)."""
    if device is None:
        device = next(model.parameters()).device.type
    tokens = tokens.to(device)
    seq_len = tokens.shape[1]

    with torch.no_grad():
        _, cache = model.run_with_cache(
            tokens,
            names_filter=lambda n: f"blocks.{layer}.attn.hook_attn" in n or f"blocks.{layer}.attn.hook_pattern" in n,
            return_type=None,
        )
    attn_key = f"blocks.{layer}.attn.hook_attn"
    if attn_key not in cache:
        attn_key = f"blocks.{layer}.attn.hook_pattern"
    attn = cache[attn_key][0, head].cpu().numpy()

    if token_labels is None:
        try:
            token_labels = [model.tokenizer.decode([t]) for t in tokens[0].cpu().tolist()]
        except Exception:
            token_labels = [str(t) for t in tokens[0].cpu().tolist()]

    fig, ax = plt.subplots(figsize=(max(6, seq_len * 0.4), max(5, seq_len * 0.4)))
    im = ax.imshow(attn, cmap="viridis", vmin=0, vmax=1, aspect="auto")
    plt.colorbar(im, ax=ax, label="Attention weight")
    ax.set_xticks(range(seq_len)); ax.set_xticklabels(token_labels, rotation=90, fontsize=LABEL_FONTSIZE)
    ax.set_yticks(range(seq_len)); ax.set_yticklabels(token_labels, fontsize=LABEL_FONTSIZE)
    ax.set_xlabel("Key position", fontsize=LABEL_FONTSIZE)
    ax.set_ylabel("Query position", fontsize=LABEL_FONTSIZE)
    ax.set_title(title or f"Attention: L{layer}H{head}", fontsize=TITLE_FONTSIZE)
    plt.tight_layout()
    if save_path: _save(fig, save_path)
    return fig


def plot_induction_score_heatmap(
    induction_scores: np.ndarray,
    title: str = "Per-head induction scores",
    save_path: Optional[Path] = None,
) -> plt.Figure:
    """2D heatmap of per-head induction scores (Figure 3)."""
    n_layers, n_heads = induction_scores.shape
    fig, ax = plt.subplots(figsize=(max(6, n_heads * 0.7), max(3, n_layers * 0.9)))
    im = ax.imshow(induction_scores, cmap="viridis", vmin=0, vmax=1, aspect="auto")
    plt.colorbar(im, ax=ax, label="Induction score")
    ax.set_xticks(range(n_heads)); ax.set_xticklabels([f"H{h}" for h in range(n_heads)], fontsize=LABEL_FONTSIZE)
    ax.set_yticks(range(n_layers)); ax.set_yticklabels([f"L{l}" for l in range(n_layers)], fontsize=LABEL_FONTSIZE)
    ax.set_xlabel("Head", fontsize=LABEL_FONTSIZE); ax.set_ylabel("Layer", fontsize=LABEL_FONTSIZE)
    ax.set_title(title, fontsize=TITLE_FONTSIZE)
    for l in range(n_layers):
        for h in range(n_heads):
            v = induction_scores[l, h]
            ax.text(h, l, f"{v:.2f}", ha="center", va="center", fontsize=8,
                    color="white" if v < 0.5 else "black")
    plt.tight_layout()
    if save_path: _save(fig, save_path)
    return fig


def plot_induction_score_over_training(
    steps: np.ndarray,
    induction_scores: np.ndarray,
    n_layers: int,
    n_heads: int,
    title: str = "Induction score vs. fine-tuning step",
    highlight_heads: Optional[list[tuple[int, int]]] = None,
    save_path: Optional[Path] = None,
) -> plt.Figure:
    """Induction score trajectories for all heads (Figures 5 and 6).

    Args:
        steps: Checkpoint step numbers, shape [n_checkpoints].
        induction_scores: Per-checkpoint induction scores,
            shape [n_checkpoints, n_layers, n_heads].
        n_layers: Number of transformer layers.
        n_heads: Number of heads per layer.
        title: Figure title.
        highlight_heads: (layer, head) pairs to draw bold and label.
            - None: highlight nothing; draw every head at full opacity
              (no head is presumed special).
            - []: empty list. Rather than silently dimming every line
              (a latent bug if the caller's circuit-head list was
              accidentally empty, e.g. from a stale/empty upstream
              array), fall back to auto-highlighting the single head
              with the highest induction score at the LAST checkpoint,
              with a "(auto)" suffix in the legend so the fallback is
              visible to the reader.
            - non-empty list: highlight exactly these heads.
        save_path: If provided, save the figure (PDF + PNG).

    Returns:
        The matplotlib Figure.
    """
    cmap = plt.get_cmap("tab10")
    fig, ax = plt.subplots(figsize=(10, 5))

    auto_fallback = False
    if highlight_heads is not None and len(highlight_heads) == 0:
        # Empty (but not None) highlight list -- auto-fallback to the
        # highest-scoring head at the final checkpoint so the figure is
        # never silently all-dimmed.
        final_scores = induction_scores[-1]  # [n_layers, n_heads]
        top = np.unravel_index(np.argmax(final_scores), final_scores.shape)
        highlight_heads = [(int(top[0]), int(top[1]))]
        auto_fallback = True
        logger.warning(
            "plot_induction_score_over_training: highlight_heads was empty; "
            "auto-highlighting L%dH%d (highest final-checkpoint score = %.4f). "
            "Check that circuit_heads was loaded correctly upstream.",
            highlight_heads[0][0], highlight_heads[0][1],
            float(final_scores[highlight_heads[0]]),
        )

    for layer in range(n_layers):
        for head in range(n_heads):
            scores = induction_scores[:, layer, head]
            color = cmap(layer % 10)
            is_hl = highlight_heads is not None and (layer, head) in highlight_heads
            label = None
            if is_hl:
                label = f"L{layer}H{head}" + (" (auto)" if auto_fallback else "")
            ax.plot(steps, scores, color=color,
                    linewidth=2.0 if is_hl else 0.7,
                    alpha=1.0 if (highlight_heads is None or is_hl) else 0.2,
                    label=label)
    ax.axhline(0.5, color="grey", linestyle="--", linewidth=0.8, label="Circuit threshold (0.5)")
    ax.set_xlabel("Training step", fontsize=LABEL_FONTSIZE)
    ax.set_ylabel("Induction score", fontsize=LABEL_FONTSIZE)
    ax.set_ylim(-0.05, 1.05)
    ax.set_title(title, fontsize=TITLE_FONTSIZE)
    if highlight_heads:
        ax.legend(fontsize=LABEL_FONTSIZE, loc="upper right")
    plt.tight_layout()
    if save_path: _save(fig, save_path)
    return fig


def plot_phase_transition(
    steps: np.ndarray,
    induction_scores: np.ndarray,
    transitions: list[dict],
    layer: int,
    head: int,
    save_path: Optional[Path] = None,
) -> plt.Figure:
    """Single-head induction score with phase transitions marked (Figure 7)."""
    curve = induction_scores[:, layer, head]
    head_t = [t for t in transitions if t["layer"] == layer and t["head"] == head]
    fig, ax = plt.subplots(figsize=(9, 4))
    ax.plot(steps, curve, color="steelblue", linewidth=1.8, label=f"L{layer}H{head}")
    for t in head_t:
        ax.axvline(t["step"], color="red", linestyle="--", linewidth=1.2, alpha=0.7)
        ax.annotate(f"Δ={t['delta']:+.2f}", xy=(t["step"], t["score_after"]),
                    xytext=(t["step"] + max(steps) * 0.02, t["score_after"] + 0.05),
                    fontsize=8, color="red")
    ax.set_xlabel("Training step", fontsize=LABEL_FONTSIZE)
    ax.set_ylabel("Induction score", fontsize=LABEL_FONTSIZE)
    ax.set_ylim(-0.05, 1.05)
    ax.set_title(f"Phase transition: L{layer}H{head}", fontsize=TITLE_FONTSIZE)
    ax.legend(fontsize=LABEL_FONTSIZE)
    plt.tight_layout()
    if save_path: _save(fig, save_path)
    return fig


def plot_adversarial_results(
    probe_scores: dict[str, float],
    title: str = "Adversarial probe results",
    save_path: Optional[Path] = None,
) -> plt.Figure:
    """Bar chart of normalised logit diff across adversarial probes (Figure 8)."""
    names = list(probe_scores.keys())
    values = [probe_scores[n] for n in names]
    colors = ["steelblue" if v >= 0 else "tomato" for v in values]
    fig, ax = plt.subplots(figsize=(max(8, len(names) * 0.5), 5))
    ax.bar(range(len(names)), values, color=colors)
    ax.axhline(1.0, color="green", linestyle="--", linewidth=1.0, label="Clean baseline (1.0)")
    ax.axhline(0.0, color="grey", linestyle="--", linewidth=0.8, label="No induction (0.0)")
    ax.set_xticks(range(len(names)))
    ax.set_xticklabels(names, rotation=45, ha="right", fontsize=LABEL_FONTSIZE)
    ax.set_ylabel("Normalised logit diff", fontsize=LABEL_FONTSIZE)
    ax.set_title(title, fontsize=TITLE_FONTSIZE)
    ax.legend(fontsize=LABEL_FONTSIZE)
    plt.tight_layout()
    if save_path: _save(fig, save_path)
    return fig
